from .binary_search import BASE_BRANCH as BINARY_SEARCH_BASE_BRANCH
from .cli_calculator import BASE_BRANCH as CLI_CALCULATOR_BRANCH
from .cp import BASE_BRANCH as CP_BASE_BRANCH
from .fibonacci import BASE_BRANCH as FIBONACCI_BASE_BRANCH
from .lru_cache import BASE_BRANCH as LRU_CACHE_BRANCH
from .stack import BASE_BRANCH as STACK_BASE_BRANCH

BASE_BRANCHES = [
    "main",
    FIBONACCI_BASE_BRANCH,
    CP_BASE_BRANCH,
    STACK_BASE_BRANCH,
    LRU_CACHE_BRANCH,
    BINARY_SEARCH_BASE_BRANCH,
    CLI_CALCULATOR_BRANCH,
]
