# This workflow will run a compile check for the current project

name: Compile Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-check:
    name: Compile Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install coreutils
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: make deps
      - name: Compile check
        run: make ci-build-check