# This workflow will run graph tests

name: Graph Checks

on:
  pull_request:
    branches: [main]
    types: [labeled]
  workflow_dispatch:

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  graph-tests:
    name: Graph Tests
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.label.name == 'graph-tests' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.head_ref }}
      # - name: Install uv
      #   run: |
      #     curl -LsSf https://astral.sh/uv/install.sh | sh
      # - name: Create .env file
      #   run: echo "GOOGLE_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
      # - name: Install dependencies
      #   run: make deps
      # - name: Run tests
      #   run: make test-graphs
