name: Update Project Memory

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update_memory:
    # Only run if the PR was merged to main AND the PR title doesn't indicate it's from this workflow
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && !startsWith(github.event.pull_request.title, 'chore: Update project memory')
    runs-on: ubuntu-latest
    permissions:
      contents: write      # To commit, push, and create branches
      pull-requests: write # To create pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history, useful for git diff and potentially for the script

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make scripts executable
        run: chmod +x scripts/update_project_memory_from_pr.sh scripts/fetch_pr_details.sh

      - name: Run update project memory script
        id: run_script
        env:
          # GITHUB_TOKEN is automatically available for 'gh' or 'curl' calls to GitHub API if needed by sub-scripts.
          # GEMINI_API_KEY is passed explicitly via the -k argument to the main script.
        run: |
          echo "Running script for PR #${{ github.event.pull_request.number }} merged into main."
          bash scripts/update_project_memory_from_pr.sh \
            -k "${{ secrets.GEMINI_API_KEY }}" \
            -r "${{ github.repository }}" \
            -p "${{ github.event.pull_request.number }}"
          echo "Script finished."

      - name: Check for changes in project memory
        id: check_changes
        run: |
          git status # For logging purposes
          if git diff --quiet project_memories/global.md; then
            echo "No changes to project_memories/global.md. Skipping PR creation."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in project_memories/global.md."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push changes
        if: steps.check_changes.outputs.changed == 'true'
        id: commit_push
        run: |
          BRANCH_NAME="chore/update-memory-pr-${{ github.event.pull_request.number }}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          git checkout -b "${BRANCH_NAME}"
          git add project_memories/global.md
          git commit -m "chore: Update project memory from PR #${{ github.event.pull_request.number }}"
          git push --set-upstream origin "${BRANCH_NAME}"
          echo "Changes committed and pushed to branch ${BRANCH_NAME}."

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head "${{ steps.commit_push.outputs.BRANCH_NAME }}" \
            --title "chore: Update project memory from PR #${{ github.event.pull_request.number }}" \
            --body "Automated update of project memory based on changes from PR #${{ github.event.pull_request.number }}. This PR was generated by the Update Project Memory workflow."
          echo "Pull request created."